//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string INDEX_LEFT = "index_left";
        
        public const string PINKY_LEFT = "pinky_left";
        
        public const string RIGHT_CONNECTED = "right_connected";
        
        public const string LEFT_CONNECTED = "left_connected";
        
        public const string THUMB_RIGHT = "thumb_right";
        
        public const string MIDDLE_RIGHT = "middle_right";
        
        public const string MIDDLE_LEFT = "middle_left";
        
        public const string RING_LEFT = "ring_left";
        
        public const string PINKY_RIGHT = "pinky_right";
        
        public const string INDEX_RIGHT = "index_right";
        
        public const string RING_RIGHT = "ring_right";
        
        public const string THUMB_LEFT = "thumb_left";
    }
}
